{
  pkgs,
  lib,
  config,
  inputs,
  outputs,
  myLib,
  hostName,
  ...
}:
{
  imports = [
    inputs.bash-logger.nixosModules.default
    inputs.disko.nixosModules.default
    inputs.gpu-passthrough.nixosModules.default
    inputs.gpu-passthrough.nixosModules.looking-glass
    inputs.home-manager.nixosModules.default
    inputs.hyprland.nixosModules.default
    inputs.libvirt-hooks.nixosModules.default
    inputs.monitor-detector.nixosModules.default
    inputs.nixos-facter-modules.nixosModules.facter
    inputs.nixvirt.nixosModules.default
    inputs.uwsm-launcher.nixosModules.default
    ./brother-printer.nix
    ./brother-scanner.nix
    ./calibre.nix
    ./chromium.nix
    ./conan.nix
    ./disko.nix
    ./git.nix
    ./gimp.nix
    ./gnome
    ./grim.nix
    ./grub.nix
    ./home-manager.nix
    ./home-assistant
    ./hyprland
    ./jupyterlab.nix
    ./kde
    ./kicad.nix
    ./kitty.nix
    ./kodi.nix
    ./libreoffice.nix
    #./libvirt-hooks.nix
    ./loupe.nix
    ./mosquitto.nix
    ./netbootxyz
    ./nerdfonts.nix
    ./nh.nix
    ./nix.nix
    ./nixvirt.nix
    ./openssh.nix
    ./pixiecore.nix
    ./polkit.nix
    ./samba.nix
    ./sddm
    ./slurp.nix
    ./tree.nix
    ./virtualization
    ./wayvnc.nix
    ./wireshark.nix
    ./wl-clipboard.nix
    ./wofi.nix
    ./vlc.nix
    ./vfio.nix
    ./waypipe.nix
    ./remmina.nix
    ./ripgrep.nix
    ./zsh.nix
  ];
}
