{
  pkgs,
  lib,
  config,
  inputs,
  outputs,
  myLib,
  hostName,
  ...
}:
{
  imports = [
    inputs.disko.nixosModules.default
    inputs.home-manager.nixosModules.default
    inputs.hyprland.nixosModules.default
    inputs.nixos-facter-modules.nixosModules.facter
    ./calibre.nix
    ./chromium.nix
    ./conan.nix
    ./git.nix
    ./gnome
    ./grim.nix
    ./grub.nix
    ./home-manager.nix
    ./home-assistant
    ./hyprland
    ./kde
    ./kicad.nix
    ./kitty.nix
    ./kodi.nix
    ./libreoffice.nix
    ./loupe.nix
    ./mosquitto.nix
    ./nerdfonts.nix
    ./nh.nix
    ./nix.nix
    ./openssh.nix
    ./pixiecore.nix
    ./polkit.nix
    ./sddm
    ./slurp.nix
    ./tree.nix
    ./virtualization
    ./wayvnc.nix
    ./wireshark.nix
    ./wl-clipboard.nix
    ./wofi.nix
    ./waypipe.nix
    ./remmina.nix
    ./ripgrep.nix
    ./zsh.nix
  ];
}
